\c casbin;

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS casbin.menu
(
    id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sequence integer,
    icon character varying(100) COLLATE pg_catalog."default" NOT NULL,
    router character varying(200) COLLATE pg_catalog."default" NOT NULL,
    parentid uuid,
    parentpath character varying(200) COLLATE pg_catalog."default",
    showstatus integer NOT NULL,
    status integer NOT NULL,
    memo character varying(1000) COLLATE pg_catalog."default",
    creator uuid,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone,
    deletedat timestamp with time zone,
    idstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT menu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin.menuaction
(
    id uuid NOT NULL,
    menuid uuid NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idstring character varying(200) COLLATE pg_catalog."default",
    menuidstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT menuaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin.menuactionresource
(
    id uuid NOT NULL,
    actionid uuid NOT NULL,
    method character varying(20) COLLATE pg_catalog."default" NOT NULL,
    path character varying(200) COLLATE pg_catalog."default" NOT NULL,
    idstring character varying(200) COLLATE pg_catalog."default",
    actionidstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT menuactionresource_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin.role
(
    id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sequence integer,
    memo character varying(1000) COLLATE pg_catalog."default",
    status integer NOT NULL,
    creator uuid,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone,
    deletedat timestamp with time zone,
    idstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin.rolemenu
(
    id uuid NOT NULL,
    roleid uuid NOT NULL,
    menuid uuid NOT NULL,
    actionid uuid NOT NULL,
    idstring character varying(200) COLLATE pg_catalog."default",
    roleidstring character varying(200) COLLATE pg_catalog."default",
    menuidstring character varying(200) COLLATE pg_catalog."default",
    actionidstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT rolemenu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin."user"
(
    id uuid NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    realname character varying(200) COLLATE pg_catalog."default",
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    status integer NOT NULL,
    creator uuid,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone,
    deletedat timestamp with time zone,
    idstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS casbin.userrole
(
    id uuid NOT NULL,
    userid uuid NOT NULL,
    roleid uuid NOT NULL,
    idstring character varying(200) COLLATE pg_catalog."default",
    useridstring character varying(200) COLLATE pg_catalog."default",
    roleidstring character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT userrole_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS casbin.menuaction
    ADD CONSTRAINT menuaction_menuid_fkey FOREIGN KEY (menuid)
    REFERENCES casbin.menu (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.menuactionresource
    ADD CONSTRAINT menuactionresource_actionid_fkey FOREIGN KEY (actionid)
    REFERENCES casbin.menuaction (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.rolemenu
    ADD CONSTRAINT rolemenu_actionid_fkey FOREIGN KEY (actionid)
    REFERENCES casbin.menuaction (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.rolemenu
    ADD CONSTRAINT rolemenu_menuid_fkey FOREIGN KEY (menuid)
    REFERENCES casbin.menu (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.rolemenu
    ADD CONSTRAINT rolemenu_roleid_fkey FOREIGN KEY (roleid)
    REFERENCES casbin.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.userrole
    ADD CONSTRAINT userrole_roleid_fkey FOREIGN KEY (roleid)
    REFERENCES casbin.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS casbin.userrole
    ADD CONSTRAINT userrole_userid_fkey FOREIGN KEY (userid)
    REFERENCES casbin."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;